version: '3'
services:
  db:
    image: mysql:8.0
    container_name: cuideoCandidateChallenge_mysql
    restart: always
    volumes:
      - ./data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 'test'
      MYSQL_USER: 'test'
      MYSQL_PASSWORD: 'test'
      MYSQL_DATABASE: 'test'
    ports:
      - 3306:3306
    networks:
      - symfony

  web:
    build: .
    container_name: cuideoCandidateChallenge_web
    volumes:
      - ./:/var/www/html
    environment:
      APACHE_DOCUMENT_ROOT: /var/www/html/public
    ports:
      - 80:80
    depends_on:
      - db
    networks:
      - symfony

networks:
  symfony:
    driver: bridge
