App\CuideoCandidate\Domain\Orders:
  type: entity
  repositoryClass: App\CuideoCandidate\Infrastructure\Persistence\Doctrine\Repository\DoctrineOrdersRepository
  table: orders
  id:
    id:
      type: uuid
      generator:
        strategy: uuid
  fields:
    name:
      type: string
      length: 50

